GET http://localhost:3001/api/product 
###

// Get a specific product by id
GET http://localhost:3001/api/product/6287caf0c5409e2324b8fb4a

###

POST http://localhost:3001/api/product
Content-Type: application/json

  {
    "imageId": "628ccf4f0e2585784504d4c7",
    "title": "Staycation",
    "description": "Lightweight, slim wall cabinet in antique brass-colored, thin metal with tempered glass. Metal back. Glass door with which closes with hasp. Three fixed shelves in glass with decorative edge in metal. Dimensions: Width 40.5 cm, height 60 cm, depth 15.5 cm Height between shelves 19 cm. Mounted.",
    "price": 1399,
    "category": "Storage",
    "stock": 3
  }

###

PUT http://localhost:3001/api/product/628ccfd00e2585784504d4c9
Content-Type: application/json

  {
    "title": "Staycation",
    "stock": 5
  }

###

DELETE http://localhost:3001/api/product/628b8550df072349e512bf1e
