GET http://localhost:3001/api/product 
###

// Get a specific product by id
GET http://localhost:3001/api/product/6287caf0c5409e2324b8fb4a

###

POST http://localhost:3001/api/product
Content-Type: application/json

  {
    "image": "image",
    "title": "Lorem Ipsum",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "price": 999,
    "category": ["Chairs & Stools"],
    "quantity": 1
  }

###

PUT http://localhost:3001/api/product/6287caf0c5409e2324b8fb4a
Content-Type: application/json

  {
    "title": "Lorem Ipsum haha",
    "quantity": 5
  }

  #   {
  #   "image": "image",
  #   "title": "Lorem Ipsum haha",
  #   "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  #   "price": 999,
  #   "category": ["Chairs & Stools"],
  #   "quantity": 5
  # }

###

DELETE http://localhost:3001/api/product/6287caf0c5409e2324b8fb4a
