GET http://localhost:3001/api/deliveryOption
###

POST http://localhost:3001/api/deliveryOption
Content-Type: application/json

{
"provider": "Hej", 
"cost": 0, 
"estTime": "19.00",
}

###

PUT http://localhost:3001/api/deliveryOption/1234
Content-Type: application/json

{

} 
###

DELETE http://localhost:3001/api/deliveryOption/1234
