GET http://localhost:3001/api/user
###

POST http://localhost:3001/api/user
Content-Type: application/json

{
"firstname": "David", 
"lastname": "Jensen", 
"password": "123",
"email": "erik.isak@gmail.com"
}


###

PUT http://localhost:3001/api/user/62862a31f7896b496c7b16bc
Content-Type: application/json

{
    "firstname": "Erik!!!!",
    "password": "1234"
} 
