### get all users 
GET http://localhost:3001/api/user

### create a new user
POST http://localhost:3001/api/user
Content-Type: application/json

{
"firstname": "David", 
"lastname": "Jensen", 
"password": "123",
"email": "erik.isak@gmail.com"
}

### update user 
PUT http://localhost:3001/api/user/62879adca04073c37eb4bf23
Content-Type: application/json

{
    "firstname": "Erikkkk",
    "password": "123"
} 

// Below is for sign in/out

### sign in 
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
    "email": "erik.isak@gmail.com",
    "password": "123"
} 

### sign out
DELETE http://localhost:3001/api/user/logout

### get cookie session (for testing)
GET http://localhost:3001/api/user/login