GET http://localhost:3001/api/order

###

POST http://localhost:3001/api/order
Content-Type: application/json

{
  "deliveryAddress": {
    "street": "ABC Street",
    "zipCode": "12345",
    "city": "City"
  },
  "deliveryOption": "628742cf55d8b506e565d82e",
  "phoneNumber": 1234567,
  "products": ["6284f14355d8b506e5ba2ea2", "6284f14355d8b506e5ba2ea3"],
  "paymentMethod": "Swish"
}

###

PUT http://localhost:3001/api/order/62875821a82034ed999dac4a
Content-Type: application/json

{
 "isShipped": true
} 