GET http://localhost:3001/api/order

###

POST http://localhost:3001/api/order
Content-Type: application/json

{
    "products": [
    {
        "_id": "6287cae855d8b506e5930390",
        "imageId": "628cc62ae5cd4173f113dfd1",
        "title": "Jolly",
        "description": "Stool with comfortable, shaped seat. Made of solid wood, in the Toon Wood type. Height 61 cm. Seat 40x32 cm. Seat height: 61 cm Width at the bottom 47 cm. Mounted.",
        "price": 1599,
        "category": ["Chairs & Stools"],
        "quantity": 1
    }],
    "deliveryAddress": {
        "street": "abc street", 
        "zipCode": "12345",
        "city": "Hong Kong Island"
    }, 
    "deliveryOption": {
        "_id": "628742cf55d8b506e565d82e",
        "provider": "Postnord",
        "cost": 495,
        "estTime": "3-5 Weekdays",
        "logoId": "628dedf2dcd87920d4496638"
    },
    "phoneNumber": 123,
    "paymentMethod": "Swish"
}

###

PUT http://localhost:3001/api/order/62875821a82034ed999dac4a
Content-Type: application/json

{
 "isShipped": true
} 